import React, { useState, useEffect } from 'react'
import Head from 'next/head'
import axios from 'axios'
import Zoom from 'react-medium-image-zoom'
import 'react-medium-image-zoom/dist/styles.css'
import { useRouter } from 'next/router';
import styles from '../styles/card.module.css'
import { Card } from 'react-bootstrap'

export default function Home() {
  const [students, setStudents] = useState([])

  useEffect( () => {
    axios.get('https://fejs-c7-api.herokuapp.com/api/students/?populate=*')
  .then( res => {
    console.log(res)
    setStudents([...res.data.data])
  })
  })

  const router = useRouter()

  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.card}>
        <div className={styles.wrapper}>
        {students.map((student, id) => {
            return(
              <div className={styles.dataCard} key={student.id}>
                <div className="row">
                  <div className="col">
                      <Card style={{width:'13rem'}} onClick={ () => router.push(`/student/${id}`)}>
                      { student.attributes.photo.data !== null &&
                            <Zoom>
                              <img className="card-img-top img-thumbnail"src={student.attributes.photo.data.attributes.url} />
                            </Zoom>
                          }
                          <Card.Body>
                            <Card.Text>First Name: {student.attributes.firstname}</Card.Text>
                            <Card.Text>Last Name: {student.attributes.lastname}</Card.Text>
                            <Card.Text>Location: {student.attributes.location}</Card.Text>
                          </Card.Body>
                    </Card>
                  </div>
                </div>
              </div>
            )
          })}
        </div>
      </div>
    </div>
  )
}
