import React from 'react'
import Head from 'next/head'
import { Button } from 'react-bootstrap'
import styles from "../styles/input.module.css"
import { useRef } from 'react'
import axios from 'axios'



export default function input() {


  const inputFirstname = useRef();
  const inputLastname = useRef();
  const inputLocation = useRef();
  const inputPhoto = useRef();
  const handleSubmit = async (event) => {
    event.preventDefault();
    const user = {
      firstname: inputFirstname.current.value,
      lastname: inputLastname.current.value,
      location: inputLocation.current.value
    }
    // console.log(user)
    console.log(inputPhoto.current.files);
    const formData = new FormData();
    formData.append('data', JSON.stringify(user))
    Array.from(inputPhoto.current.files).forEach(file => {
      formData.append('files.photo', file, file.name)
    })
    const res = await
      axios.post('https://fejs-c7-api.herokuapp.com/api/students/', formData)
    console.log(res.data)

  };
  return (
    <div className={styles.input}>
      <Head>
        <title>Input</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.inputForm}>
        <h2 className={styles.formHeader} style={{ textAlign: "center" }}>Input Page</h2>
        <form onSubmit={handleSubmit} action="/" method="post" className={`${styles.form} ${'p-5'}`}>
          <label><b>First Name</b></label>
          <input type="text" id="firstname" name="firstname" ref={inputFirstname} className={styles.formfield} />
          <label><b>Last Name</b></label>
          <input type="text" id="lastname" name="lastname" ref={inputLastname} className={styles.formfield} />
          <label><b>Location</b></label>
          <input type="text" id="location" name="location" ref={inputLocation} className={styles.formfield} />
          <label>Photo</label>
          <input type="file" id="photo" name="photo" ref={inputPhoto} />
          {/* <Button type="submit" className={styles.btn}>Submit Form</Button> */}
          <input type="submit" className={styles.btn} value="Submit" />
        </form>
      </div>
    </div>
  )
}